integrations:
  prometheus_remote_write:
  - basic_auth:
      password: eyJrIjoiZGRkNzRhMTJlZjMwNWE4YjZiYTljNjMzYjAyNjRhNjUzY2FmOTgwMSIsIm4iOiJzdGFjay00MzQxMzEtZWFzeXN0YXJ0LXByb20tcHVibGlzaGVyIiwiaWQiOjcwODE0MX0=
      username: 569033
    url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
  windows_exporter:
    enabled: true
logs:
  configs:
  - clients:
    - basic_auth:
        password: eyJrIjoiZGRkNzRhMTJlZjMwNWE4YjZiYTljNjMzYjAyNjRhNjUzY2FmOTgwMSIsIm4iOiJzdGFjay00MzQxMzEtZWFzeXN0YXJ0LXByb20tcHVibGlzaGVyIiwiaWQiOjcwODE0MX0=
        username: 283486
      url: https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push
    name: integrations
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
    - job_name: integrations/windows-exporter-application
      pipeline_stages:
      - json:
          expressions:
            source: source
      - labels:
          source: 
      relabel_configs:
      - source_labels:
        - computer
        target_label: agent_hostname
      windows_events:
        bookmark_path: C:\Users\ESGI\AppData\Roaming\bookmark-application.xml
        eventlog_name: Application
        labels:
          job: integrations/windows_exporter
        use_incoming_timestamp: true
        xpath_query: '*'
    - job_name: integrations/windows-exporter-system
      pipeline_stages:
      - json:
          expressions:
            source: source
      - labels:
          source: 
      relabel_configs:
      - source_labels:
        - computer
        target_label: agent_hostname
      windows_events:
        bookmark_path: C:\Users\ESGI\AppData\Roaming\bookmark-system.xml
        eventlog_name: System
        labels:
          job: integrations/windows_exporter
        use_incoming_timestamp: true
        xpath_query: '*'
    target_config:
      sync_period: 10s
metrics:
  configs:
  - name: integrations
    remote_write:
    - basic_auth:
        password: eyJrIjoiZGRkNzRhMTJlZjMwNWE4YjZiYTljNjMzYjAyNjRhNjUzY2FmOTgwMSIsIm4iOiJzdGFjay00MzQxMzEtZWFzeXN0YXJ0LXByb20tcHVibGlzaGVyIiwiaWQiOjcwODE0MX0=
        username: 569033
      url: https://prometheus-prod-01-eu-west-0.grafana.net/api/prom/push
  global:
    scrape_interval: 60s
  wal_directory: /tmp/grafana-agent-wal

